#!/bin/bash

#Enviroment variables
#SOCAT_IP_DSTADDR
#SOCAT_IP_IF
#SOCAT_IP_LOCADDR
#SOCAT_PEERADDR
#SOCAT_PEERPORT

echo "$SOCAT_IP_DSTADDR, $SOCAT_IP_IF, $SOCAT_IP_LOCADDR, $SOCAT_PEERADDR, $SOCAT_PEERPORT"
tput bel